name: Purge Old Traffic Data (keep 2 days)

on:
  schedule:
    - cron: "17 3 */2 * *"   # Every 2 days at 03:17 UTC
  workflow_dispatch: {}

jobs:
  purge:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Sanity - check required secrets
        run: |
          test -n "${{ secrets.POSTGREST_URL }}" || (echo "POSTGREST_URL secret missing" && exit 1)
          test -n "${{ secrets.SERVICE_KEY }}"   || (echo "SERVICE_KEY secret missing" && exit 1)

      - name: "Call RPC: api.purge_old_traffic(2)"
        env:
          POSTGREST_URL: ${{ secrets.POSTGREST_URL }}
          SERVICE_KEY:   ${{ secrets.SERVICE_KEY }}
        run: |
          curl -s -X POST "$POSTGREST_URL/rpc/purge_old_traffic" \
            -H "apikey: $SERVICE_KEY" \
            -H "Authorization: Bearer $SERVICE_KEY" \
            -H "Content-Type: application/json" \
            -d '{"p_keep_days":2}'
